version: "3.9"
services:
  db:
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: sh -c "rails db:create && rails db:migrate && rails db:reset && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - backend

  web:
    image: nginx:1.23.1-alpine
    ports:
      - 8080:8080
    volumes:
      - './nginx-app-prod.conf:/etc/nginx/conf.d/${APP_NAME}.conf'
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge
