version: "3.9"
services:
  app:
    user: ${APP_USER_ID}:${APP_GROUP_ID}
    command: sh -c "bin/rails db:create && bin/rails db:migrate && rm -f tmp/pids/server.pid && bundle exec bin/dev"
    ports:
      - "3000:3000"
